/**
  * @Created Date 04/24/2019
  * @author    OASISFINANCIAL GROUP
  * @copyright Copyright (c) 2019-2020 
  * @license   
  * @Modified Date
  * @Description 
*/
public class Constant {
    
    
    public static final String CASHTRAX_QA = 'CashTrax_QA';
    public static final String CASHTRAX_UAT = 'CashTrax_UAT';
    public static final String CASHTRAX_STAGING = 'CashTrax_SATGING';
    public static final String CASHTRAX_PRODUCTION = 'CashTrax_PRODUCTION';
    public static final String RESPONSE_FAIL = '200:Fail';
    public static final String RESPONSE_SUCCESS = '200:Success';
    
    
    public static final String RC_ATTORENY_ACCOUNT = 'Attorney';
	public static final String RC_PROVIDER_ACCOUNT= 'Provider';
	public static final String RC_ATTORENY_CONTACT = 'Attorney';
	public static final String RC_PROVIDER_CONTACT = 'Provider';

    
}