/**********************************************************
    *@author             : 
    *@Version            : V 1.0
    *@Description        : Handle non-attorney trigger actions
    *@Test class         :
    **********************************************************/
public class NonAttorneyTriggerUtilityHandler {
    
    
    public static void UpdateRole(List<Non_Attorney_Contact__c> arList) {
        
     /*   
        for(Non_Attorney_Contact__c relation: arList)
        {
            PresetSalesforceToCasthraxController.UpdateContactCTX(relation.Contact__c, relation.Id);
        
        
            MedlienSalesforceToSystemsController.UpdateContactML(relation.Contact__c, relation.Id);
        
        
        }
        
        */
        
    }
    
}