@isTest
private class TestPaymentTxn {
  @isTest(SeeAllData=true)
  static void testHelper(){
    Helper hp = new Helper();
    Helper.abc1();
    Helper.abc();
    Helper.abc2();
    Helper.abc3();
    Helper.abc4();
    Helper.abc5();
    Helper.abc6();
    Helper.abc7();
    Helper.abc8();
    Helper.abc9();
    Helper.abc10();
    Helper.abc11();
    Helper.abc12();
    Helper.abc13();
    Helper.abc14();
    Helper.abc15();
    Helper.abc16();
    Helper.abc17();
    Helper.abc18();
   }
}